newest changes

diff --git a/universal-review~ b/universal-review~
--- a/universal-review~
+++ b/universal-review~
@@ -36,38 +36,23 @@ cyarev=${rev}$(tput setaf 6)
 ylwrev=${rev}$(tput setaf 3)
 blurev=${rev}$(tput setaf 4)
 
-write_config() {
-    echo "safety=1" >> ${GPDIR}/config
-    echo "username=not_set" >> ${GPDIR}/config
-    echo "teamCHOICE=none" >> ${GPDIR}/config
-    echo "gerritTEAM=:" >> ${GPDIR}/config
-    echo "gerritURL=;" >> ${GPDIR}/config
-}
-
 do_checks(){
-    [[ ! -d ${GPDIR} ]] && mkdir -p ${GPDIR} && sleep .5
-    [[ ! -f ${GPDIR}/config ]] && write_config
+    [[ ! -d ${GPDIR} ]] && mkdir -p ${GPDIR}; sleep .5
+    [[ ! -f ${GPDIR}/safety ]] && echo "1" > ${GPDIR}/safety
     [[ ! -f ${ARRY} ]] && curl http://pac-rom.com/downloads/projects > ${ARRY}
-    safety=$(get safety)
-}
-
-get(){
-    grep $1 ${GPDIR}/config | cut -d "=" -f2
-}
-
-save(){
-    x=$(get $1)
-    sed -i "s#$x#$2#" ${GPDIR}/config
+    safety=$(cat ${GPDIR}/safety)
 }
 
 user(){
-    clear; [[ "$(get username)" == "not_set" ]] && set_up_user || GUZER=$(get username)
+    clear; [[ -f ${HOME}/.gerritpush/username ]] && \
+    GUZER=$(cat ${HOME}/.gerritpush/username) || set_up_user
 }
+
 
 set_up_user(){
     do_checks
-    if [ "$(get username)" != "not_set" ]; then    
-        GUZER=$(get username)
+    if [ -f ${GPDIR}/username ]; then
+        GUZER=$(cat ${GPDIR}/username)
         echo ""
         echo "###################################################################"
         echo ""
@@ -80,37 +65,35 @@ set_up_user(){
         read -p "Please enter your Gerrit UserName: " GUZER; clear
         if [ ${safety} -eq "1" ]; then
             while true; do
-                read -p "Your entered ${GUZER}. Is this correct? (Yes/No) " correct1
+                read -p "Your entered ${GUZER}.  Is this correct? (Yes/No) " correct1
                 case ${correct1} in
-                    Y*|y*|"") clear; save username ${GUZER}; clear;
+                    Y*|y*|"") clear; echo ${GUZER} > ${GPDIR}/username; clear;
                               echo "Your new gerrit username is: ${GUZER}"; break ;;
                        N*|n*) clear; read -p "Re-Enter Gerrit UserName: " GUZER
-                              save username ${GUZER}; clear
+                              echo ${GUZER} > ${GPDIR}/username; clear
                               echo "Your new gerrit username is: ${GUZER}"; break ;;
                            *) clear; echo "Invalid Entry \"${correct1}\", Please enter y/yes or n/no";;
                 esac
             done
           else
-            save username ${GUZER};
+            echo ${GUZER} > ${GPDIR}/username;
             clear;
         fi
     fi
 }
 
 team() {
-    if [ "$(get teamCHOICE)" !=  "none" ]; then
-        TEAM=$(get teamCHOICE)
-        GTEAM=$(get gerritTEAM)
-        GURL=$(get gerritURL)
-      else
-        new_team
-    fi
+    if [ ! -f ${GPDIR}/team ]; then
+        echo "NULL" > ${GPDIR}/team && GTEAM=$(cat ${GPDIR}/team)
+        echo "NULL" > ${GPDIR}/teamCHOICE && ${DisplayTeam}=$(cat ${GPDIR}/teamCHOICE) &> /dev/null
+        [[ -f ${GPDIR}/gerritURL ]] && GURL=$(cat ${GPDIR}/gerritURL) || new_team
+fi
 }
 
 new_team() {
     do_checks
-    if [ "$(get teamCHOICE)" == "none" ]; then
-        DisplayTeam=$(get teamCHOICE)
+    if [ -f ${GPDIR}/team ]; then
+        DisplayTeam=$(cat ${GPDIR}/teamCHOICE)
         echo ""
         echo "###################################################################"
         echo ""
@@ -119,31 +102,40 @@ new_team() {
         echo "###################################################################"
         echo ""
     fi
-
     echo "Please Select your new Gerrit Team:"
-    echo ""
-    max=$(echo ${#TEAM[@]})
-    for (( i=0; i<${max}; i++ )); do
-        (( h = $i + 1 ))
-        echo "$h) ${bldcya}${TEAM[$i]}${txtrst}"
+    echo "Enter the Corresponding Number"
+    select NUMBER in $(echo ${bldcya}${TEAM[@]}${txtrst}); do
+        case ${NUMBER} in
+            ${TEAM[0]}) i=0; break ;;
+            ${TEAM[1]}) i=1; break ;;
+            ${TEAM[2]}) i=2; break ;;
+            ${TEAM[3]}) i=3; break ;;
+            ${TEAM[4]}) i=4; break ;;
+            ${TEAM[5]}) i=5; break ;;
+            ${TEAM[6]}) i=6; break ;;
+            ${TEAM[7]}) i=7; break ;;
+            ${TEAM[8]}) i=8; break ;;
+            ${TEAM[9]}) i=9; break ;;
+           ${TEAM[10]}) i=10; break ;;
+           ${TEAM[11]}) i=11; break ;;
+           ${TEAM[12]}) i=12; break ;;
+           ${TEAM[13]}) i=13; break ;;
+           ${TEAM[14]}) i=14; break ;;
+           ${TEAM[15]}) i=15; break ;;
+           ${TEAM[16]}) i=16; break ;;
+           ${TEAM[17]}) i=17; break ;;
+           ${TEAM[18]}) i=18; break ;;
+           ${TEAM[19]}) i=19; break ;;
+            *) echo "Invalid Entry \"${NUMBER}\", Please enter from the options provided."; 
+               echo ""; echo ""; 
+               team; break;;
+        esac
     done
-    echo ""
-    while true; do
-        read -p "Enter the Corresponding Number: " NUMBER
-        if [ ${NUMBER} -le $max ] && [ ${NUMBER} -ne 0 ]; then
-            case ${NUMBER} in
-                *) (( i = ${NUMBER} - 1 )); break ;;
-            esac
-        else
-            echo "\"${NUMBER}\" is not a valid selection"
-        fi 2>/dev/null
-    done
-    
-    save teamCHOICE ${TEAM[$i]}
-    save gerritTEAM ${GTEAM[$i]}
-    save gerritURL ${URL[$i]}
 
-    sleep 1; clear;
+    echo ${GTEAM[$i]} > ${GPDIR}/team;
+    echo ${TEAM[$i]} > ${GPDIR}/teamCHOICE;
+    echo ${URL[$i]} > ${GPDIR}/gerritURL;
+    sleep 1; clear; 
     echo "Default Set to ${bldcya}${TEAM[i]}${txtrst}"; echo
 }
 
@@ -152,19 +144,19 @@ correct_commit() {
     while true; do
         echo ${MSSG}; echo
         read -p "Is this correct ??" correct2
-        case ${correct2} in
-            *|y*|"") echo "Commit set to ${bldcya}${MSSG}${txtrst}"; break ;;
-              N*|n*) read -p "Re-enter commit message" MSSG ;;
-                  *) clear; echo "Invalid Entry \"${correct2}\". Please enter y/yes or n/no" ;;
-        esac
+       case ${correct2} in
+            Y*|y*|"") echo "Commit set to ${bldcya}${MSSG}${txtrst}"; break ;;
+               N*|n*) read -p "Re-enter commit message" MSSG ;;
+                   *) clear; echo "Invalid Entry \"${correct2}\". Please enter y/yes or n/no" ;;
+       esac
     done
 }
 
 push_stuff(){
-    GUZER=$(get username)
-    GTEAM=$(get gerritTEAM)
-    GURL=$(get gerritURL)
+    GUZER=$(cat ${GPDIR}/username)
+    GTEAM=$(cat ${GPDIR}/team)
     BRANCH=$(git branch | sed -n '/\* /s///p')
+    GURL=$(cat ${GPDIR}/gerritURL)
     PROJECT=$(grep "projectname" .git/config | awk -F "projectname = " '{print $2}' | sed -e 's/^[ \t]*//' )
     [[ -z ${PROJECT} ]] && PROJECT=$(grep "url" .git/config | awk -F "url = " '{print $2}' | rev | cut -d/ -f1 | rev | cut -d. -f1)
     git push ssh://${GUZER}@${GTEAM}${GURL}${PROJECT} HEAD:refs/\for/${BRANCH}
@@ -177,7 +169,7 @@ push() {
             read -p "Are you sure you want to push? (Y/n): " RESP
             case ${RESP} in
                 Y*|y*|"") push_stuff; break ;;
-                       *) echo "Canceled"; break ;;
+                       *) echo "Canceled"; break ;; 
             esac
         done
       else
@@ -224,7 +216,7 @@ amend() {
         read -p "Have you edited the files?/Do you want to change commit message? (Y/n): " RESPa
         case ${RESPa} in
             Y*|y*|"") git add -A; git commit --amend; push; break ;;
-               N*|n*) echo "Please edit them and press [ENTER] when finished,"
+               N*|n*) echo "Please edit them and press [ENTER] when finished," 
                       read -p "or press \"0\" to quit and come back later: "; answer
                       case $answer in
                           "") : ;;
@@ -245,11 +237,11 @@ correct_gname() {
     while true; do
         read -p "Your entered ${bldcya}${GUZER}${txtrst}, is this correct? " correct1
         case ${correct1} in
-            Y*|y*|"") save username ${GUZER};
+            Y*|y*|"") echo ${GUZER} > ${GPDIR}/username; 
                       echo "Your new gerrit username is: ${GUZER}"; break ;;
-               N*|n*) read -p "Re-Enter Gerrit UserName: " GUZER;
-                      save username ${GUZER}; echo "Your new gerrit username is: ${GUZER}"; break ;;
-                   *) clear; echo "Invalid Entry ${correct1}. Please enter y/yes or n/no" ;;
+               N*|n*) read -p "Re-Enter Gerrit UserName: " GUZER; 
+                      echo ${GUZER} > ${GPDIR}/username; echo "Your new gerrit username is: ${GUZER}"; break ;;
+                   *) clear; echo "Invalid Entry ${correct1}.  Please enter y/yes or n/no" ;;
         esac
     done
 }
@@ -258,10 +250,9 @@ nameq_question() {
     echo "Enter an option:"
     select NAME in "View your current gerrit username" "Enter a New gerrit username"; do
         case ${NAME} in
-            *View*) GUZER=$(get username) \
-                      && echo "Your current gerrit username is: ${bldcya}${GUZER}${txtrst}" \
-                      || echo "No gerrit username found.."; break ;;
-             *New*) read -p "Enter your new gerrit username: " GUZER;
+            *View*) [[ -f ${GPDIR}/username ]] && echo "Your current gerrit username is: ${bldcya}${GUZER}${txtrst}" \
+                    || echo "No gerrit username found.."; break ;;
+             *New*) read -p "Enter your new gerrit username: " GUZER; 
                     [[ ${safety} -eq "1" ]] && correct_gname; break ;;
                 * ) echo "That is not a valid option (Choose 1 or 2)";
         esac
@@ -304,12 +295,12 @@ new() {
 }
 
 update_stuff(){
-    rm -f ${GPDIR}/universal-review;
-    mv ${GPDIR}/.new ${HOME}/bin/universal-review;
-    chmod +x ${HOME}/bin/universal-review;
-    rm -f ${GPDIR}/teamProjects;
-    mv ${GPDIR}/.newproject ${HOME}/bin/teamProjects;
-    chmod +x ${HOME}/bin/teamProjects; echo;
+    rm -f ${GPDIR}/universal-review; 
+    mv ${GPDIR}/.new ${HOME}/bin/universal-review; 
+    chmod +x ${HOME}/bin/universal-review; 
+    rm -f ${GPDIR}/teamProjects; 
+    mv ${GPDIR}/.newproject ${HOME}/bin/teamProjects; 
+    chmod +x ${HOME}/bin/teamProjects; echo; 
     echo "Successfully updated to v${NEWV}!";
 }
 
@@ -362,8 +353,8 @@ safety() {
                       echo "Turn ${bldcya}(On)${txtrst} or ${bldred}(Off)${txtrst}?";
                       select safety1 in "On" "Off"; do
                           case ${safety1} in
-                              On) save safety 1; break ;;
-                             Off) save safety 0; break ;;
+                              On) echo "1" > ${GPDIR}/safety; break ;;
+                             Off) echo "0" > ${GPDIR}/safety; break ;;
                                *) clear; echo "Invalid Entry ${safety1}, Please re-try";;
                           esac
                       done ;;
@@ -381,17 +372,19 @@ setup() {
 error() {
     echo "###################################################################"
 
-    DisplayUser=$(get username) && echo "Your gerrit username is: ${bldcya}${DisplayUser}${txtrst}"
-    DisplayCHOICE=$(get teamCHOICE) && echo "Your gerrit team is set to: ${bldcya}${DisplayCHOICE}${txtrst}"
-    [[ $(get safety) == "1" ]] && DisplaySafety="On" || DisplaySafety="Off" 
-    echo "Your Safety Checks are set to: ${bldcya}${DisplaySafety}${txtrst}"
+    [[ -f ${GPDIR}/username ]] && DisplayUser=$(cat ${HOME}/.gerritpush/username) && \
+        echo "Your gerrit username is: ${DisplayUser}"
+    [[ -f ${GPDIR}/team ]] && DisplayCHOICE=$(cat ${GPDIR}/teamCHOICE) && \
+        echo "Your gerrit team is set to: ${DisplayCHOICE}"
+    [[ -f ${GPDIR}/safety ]] && [[ $(cat ${GPDIR}/safety) == "1" ]] && DisplaySafety="On" || DisplaySafety="Off"
+        echo "Your Safety Checks are set to: ${bldcya}${DisplaySafety}${txtrst}"
 
     echo ${bldylw}"###################################################################"
     sleep 4;
     echo "#                                                                 #"
     echo "# Universal Gerrit Review                                         #"
     echo "#                                                                 #"
-    echo "# Created by Sniper/Goldflame09/wedgess/Papa Smurf151/soupmagnet  #"
+    echo "# Created by Sniper/Goldflame09/wedgess/Papa Smurf151/Soupmagnet  #"
     echo "#                                                                 #"
     echo "# A PAC-man Project                                               #"
     echo "#                                                                 #"
